version: '3.8'
services:
  keuangan:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true  # Keep stdin open
    tty: true         # Allocate a pseudo-TTY
    image: ghcr.io/haetsugaya/kelas-onxp-python-group5-task4:latest
    volumes:
      - .:/app